### ISSUE TITLE
Unable to change the position of okay button.

### ISSUE THREAD

**Issue by mkpazon** [amlcurran/ShowcaseView#125]
There are times that I want to showcase a view at the lower right of the screen. And since by default the "OK" button is on the lower right, this button becomes invisible because of the showcase circle.

I assume that I have to put a LayoutParams to ConfigOptions' buttonLayoutParams however ShowcaseView does not read the ConfigOptions I create but instead creates a new ConfigOptions with the default values

**Comment by santafebound** [comment]
I don't feel like this adequately addressed the question. And the .setButtonPosition() method doesn't seem to exist for the ShowcaseView object, as indicated above. How can I move the button now?

**Comment by pavelsust** [comment]
Now how i can change the button position??

ShowCase.setButtonPosition();

What should i write there??
