### ISSUE TITLE
How to change the color scheme

### ISSUE THREAD

**Issue by arashkav** [amlcurran/ShowcaseView#159]
I know that my question might not be considered an issue so please let me know if I should close it.
I want to know how to change color scheme of my showcaseview.

**Comment by JamieFarrelly** [comment]
@amlcurran That sample leads to a 404 now, I can't see an easy way to change the colors at the moment, is there a new way of doing it? I'd be up for adding this feature in if it's needed.

**Comment by amlcurran** [comment]
@JamieFarrelly it is pretty easy you can just set the style on the showcase view:
https://github.com/amlcurran/ShowcaseView/blob/master/sample/src/main/java/com/github/amlcurran/showcaseview/sample/MainActivity.java#L100
