### ISSUE TITLE
Contextual Action Bar

### ISSUE THREAD

**Issue by rcketscientist** [amlcurran/ShowcaseView#160]
ShowcaseView currently does not work for contextual action bars.  When it tries to look up the view it will fail with NPE.  I previously had a hack in that reverted to the overflow in this case but recently updated to the latest since the improvements sounded worth the effort.  They were, it's come a long way, but when using this for a tutorial I would think contextual views would be useful to more than just me.

I'll take a closer look to see if I can fix this myself in the next day or two.

**Comment by rcketscientist** [comment]
I saw a flurry of closed issues, but didn't see an explicit reason.  I know
you wanted to make some significant changes to the library for 5.0+ and I
see a lot of new activity.  Are these issues irrelevant now?  If so how do
the changes relate to the prior headaches some of the Android changes
created?

**Comment by amlcurran** [comment]
I have closed all old issues to give myself a cleaner slate to work with, meaning I can properly investigate and prioritise issues as required, with a better process.

If you'd like this to be considered again, please raise another issue (or reopen this, I guess).

Thanks!

**Comment by rcketscientist** [comment]
OK, I can understand that.  Have the fundamental changes you envisioned
been implemented yet?  In other words, would it be worth it to compare my
fork at this point or wait a bit longer?  I had a fairly complex use-case
for the library so I can really run it through the gauntlet, but I'm short
on time at the moment so I'd prefer to wait until the new framework is in
place.

**Comment by amlcurran** [comment]
Yup mostly! The main thing I wanted to implement was the Target API, which has been available for some time. 

What is your use case out of interest?

**Comment by rcketscientist** [comment]
Basically it's a step by step tutorial involving a gallery and a dozen or
so action items including contextual action items.  The user is guided
through making selections and interacting with the user interface.  It
ideally highlights any visible (contextual) action items and falls back on
highlighting (and showing) the overflow menu so the user can find and
execute functionality regardless of how the device ends up laying out the
UI.  I believe contextual broke somewhere along the way to 5.0.  I think a
lot of the other stuff was simple workarounds outside the library.  I'll
update my fork and give it a shot this week.  If you like I'll share any
application code that I use for some of the extraneous functionality if
it's still needed; might be helpful in a demo, etc.

**Comment by rcketscientist** [comment]
I'm not the best with collaborating in git, after merging your changes a
pull request seems to be showing all your changes as well, so I don't
really want to post that until I understand whats wrong.  Basically here
are the changes:

   - ActionItemTarget - Will automatically return overflow if the action
   item is null.
   - ActionViewTarget - Some crash reports showed a null overflow, so added
   handling for this.
   - StandardShowcaseDrawer - Allowed access to the scale matrix so the
   size of the showcase could be changed manually.


If those sound worthwhile I'll try and figure out why the PR is a mess.
The following link contains some convenience wrappers for SCV that might be
useful in samples:

https://gist.github.com/rcketscientist/ae976eb08d8ace762d55

One thing I was never able to get working was showcasing the
ShareActionProvider.  Any ideas on that front?
