### ISSUE TITLE
Bug: text is obscured by the button someties

### ISSUE THREAD

**Issue by michaelitvin** [amlcurran/ShowcaseView#184]
Suppose the button is at the bottom right, as is the default. If the largest available area is also at the bottom, then the text is aligned to the bottom of the screen, thus getting obscured by the button.

SGS2 running Android 4.1.2 AllianceROM

![screenshot_2014-05-22-23-47-59 2](https://cloud.githubusercontent.com/assets/5813969/3060141/a5c82a24-e1f4-11e3-904b-a4c1906d746e.png)

**Comment by brainvision** [comment]
still present.. :(
