### ISSUE TITLE
Android Studio/gradle unfriendly

### ISSUE THREAD

**Issue by 2dwarfs** [amlcurran/ShowcaseView#186]
The projects is very good, but please make it more Android Studio friendly. 
Gradle says that the dependency "com.github.amlcurran.showcaseview:library:+5.0.0-SNAPSHOT" does not exist. 

Then when importing the project as module it says:
 No such property: GROUP for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

thanks

**Comment by vyscond** [comment]
amicurran how can we solve the problem of @hectorC

**Comment by BoldijarPaul** [comment]
@vyscond  +1

**Comment by apuder** [comment]
Copy ShowcaseView/gradle.properties to your root directory and add this to your settings.gradle:

include ':app', ':ShowcaseView'
project(':ShowcaseView').projectDir = new File('ShowcaseView/library')
