### ISSUE TITLE
Multiple targets on same screen

### ISSUE THREAD

**Issue by BeniG** [amlcurran/ShowcaseView#218]
Hi Amlcurran,

Thanks for all of your great work
Just want to know if you going to add option for Multiple targets on same screen
you said if people ask you for it you will add it :)

Thanks in advanced

**Comment by paulcanning** [comment]
@saltcoffee could you post how you are doing multiple targets on the same screen?

**Comment by saltcoffee** [comment]
@paulcanning i add a constructed function in class ShowcaseView.Builder. add a res array param.

like this:

```

    public int[] mRes;
    public int mIndex = 1;
    public View mView;
    public static class Builder {

        final ShowcaseView showcaseView;
        private final Activity activity;
        private int[] mRes;
        private View mView;

        public Builder(Activity activity, int[] res, View view) {
            this(activity, false);
            mRes = res;
            mView = view;
        }
        
        public Builder(Activity activity, View view) {
            this(activity, false);
            mView = view;
        }

        public Builder(Activity activity, boolean useNewStyle) {
            this.activity = activity;
            this.showcaseView = new ShowcaseView(activity, useNewStyle);
            this.showcaseView.setTarget(Target.NONE);
        }

        /**
         * Create the {@link com.github.amlcurran.showcaseview.ShowcaseView} and show it.
         *
         * @return the created ShowcaseView
         */
        public ShowcaseView build() {
            insertShowcaseView(showcaseView, activity);
            showcaseView.mRes = mRes;
            showcaseView.mView = mView;
            return showcaseView;
        }
    .....
    .....
```

then you can judge on showcaseview ontouch method like this ：

@Override
    public boolean onTouch(View view, MotionEvent motionEvent) {

        float xDelta = Math.abs(motionEvent.getRawX() - showcaseX);
        float yDelta = Math.abs(motionEvent.getRawY() - showcaseY);
        double distanceFromFocus = Math.sqrt(Math.pow(xDelta, 2) + Math.pow(yDelta, 2));

        if (MotionEvent.ACTION_UP == motionEvent.getAction() &&
                hideOnTouch && distanceFromFocus > showcaseDrawer.getBlockedRadius()) {
        	if (mRes == null) {
        		this.hide();
        		mView.setVisibility(View.GONE);
			} else {
				if (mIndex < mRes.length) {
	                setBackgroundResource(mRes[mIndex]);
	                mIndex++;
	            } else {
	                this.hide();
	                mView.setVisibility(View.GONE);
	            }
			}

            return true;
        }

        return blockTouches && distanceFromFocus > showcaseDrawer.getBlockedRadius();
    }


someone also saied it can override onShowcaseViewHide(ShowcaseView showcaseView) or onShowcaseViewDidHide(ShowcaseView showcaseView) method, i dont try it.
