### ISSUE TITLE
Override showcase radius

### ISSUE THREAD

**Issue by ghost** [amlcurran/ShowcaseView#242]
Is it possible to override showcase radius?

**Comment by tajchert** [comment]
+1 to that.

**Comment by tajchert** [comment]
Can we get any explanation on that - why it was dropped? @amlcurran

**Comment by amlcurran** [comment]
I closed all issues which were old, to start afresh. 

This issue has now been fixed as you can supply your own custom ShowcaseDrawer now; you can pick any radius you want! The documentation isn't great I'll admit, but here is an example https://github.com/amlcurran/ShowcaseView/blob/master/sample/src/main/java/com/github/amlcurran/showcaseview/sample/CustomShowcaseActivity.java#L32

**Comment by tajchert** [comment]
Many thanks!
