### ISSUE TITLE
ShowcaseView draws on top of navigation bar

### ISSUE THREAD

**Issue by bubbleguuum** [amlcurran/ShowcaseView#246]
There's a weird bug on Lollipop:

The ShowcaseView extends vertically on all the screen height, resulting in the Showcase advance button being drawn over the new L navigation controls.

Looking into it for a possible fix, I found out that the ShowcaseView's getMeasuredHeight returns the screen height (1920 on a Nexus 5) instead of  screen height - navigation bar's height, like it is the case on KitKat.

I cannot find an explanation for this except a bug in L.
I could not think of a workaround either as overriding onMeasure() to return the correct height on L, did not fix it but resulted in other visual glitches.

Even weirder, if you look at the ShowcaseView in UI Automator, it reports the correct height for the ShowcaseView RelativeLayout although the Showcase button is drawn outside of it.

**Comment by amlcurran** [comment]
Haven't yet figured out why this is happening, but it is on my radar

**Comment by max929292** [comment]
Its not only the button that overlaps but sometimes also text so the button_margin does not really workaround this issue. Is there a way we can push the text up as well?

![screenshot_2015-01-12-07-10-14](https://cloud.githubusercontent.com/assets/10491246/5697713/30a4fb60-9a2b-11e4-926d-ed5c140118a7.png)

**Comment by sergiiz** [comment]
Any updates about this issue?

**Comment by sergiiz** [comment]
Pull request created with simple fix of this problem amlcurran/ShowcaseView#272

**Comment by max929292** [comment]
Thanks for the update.
Would it be possible to add a new release with these changes so that I can use gradle compile and get the updated Version:
compile 'com.github.amlcurran.showcaseview:library:5.0.1'

I am still learning Android development so I do not know how to manually compile the latest version myself. Thanks!

**Comment by sergiiz** [comment]
Hi guys, please try updated fix of this problem from my fork in 'upstream' branch : https://github.com/sergiiz/ShowcaseView/commits/upstream 
Now it should work properly with orientation change and hardware keyboard existance case. If you will confirm everything is fine - I'll create a new pull request for it.

**Comment by lolobosse** [comment]
Yes, it fixed the issue for me :smile: :+1: (I didn't use your fork, just copy paste your modifications, so I cannot say if all your diff with master are ok but your last commit fixed the issue). 

Here is the screenshot:

![screenshot_2015-03-08-00-01-02](https://cloud.githubusercontent.com/assets/5024077/6543699/b79d15fa-c526-11e4-9f04-da0b53b89f61.png)

Nexus 4, 5.0.1

**Comment by felipebari** [comment]
Great fix @sergiiz. Could anyone involved in the project update the Gradle release with this fix? That would make everyone's lives easier.

**Comment by sergiiz** [comment]
Hi guys, 
FYI: I saw another fix for the problem in this thread: https://github.com/SpecialCyCi/AndroidResideMenu/issues/38
so workaround could be in just adding 
<item name="android:windowDrawsSystemBarBackgrounds">false</item>
to your values-v21/styles.xml

**Comment by lolobosse** [comment]
@sergiiz Did you test it? Should I do it? BTW, did you create a pull request with your fix (the one I tested)? :smile:

**Comment by sergiiz** [comment]
@lolobosse unfortunately I haven't tried `<item name="android:windowDrawsSystemBarBackgrounds">false</item>` approach yet. Please test it if you can. For my previous fix - here was a pull request containing only portrait screen mode. Now I think that  `android:windowDrawsSystemBarBackgrounds` looks better so it make sense to create another pull request if it works fine

**Comment by lolobosse** [comment]
Ok, I just tested it and I have to say that I prefer yours @sergiiz :smile: :+1: Here is why:

The normal one on 5.0.1:
 
![screenshot_2015-03-15-21-55-35](https://cloud.githubusercontent.com/assets/5024077/6658096/cc39b14c-cb5e-11e4-9af6-f95f25c1e502.png)

The "just with style" on Android 5.0.1:

![screenshot_2015-03-15-21-55-08](https://cloud.githubusercontent.com/assets/5024077/6658101/17d25e60-cb5f-11e4-81da-42b740717f9c.png)

Your fix on Android 5.0.1:

![screenshot_2015-03-15-22-02-13](https://cloud.githubusercontent.com/assets/5024077/6658103/292e2748-cb5f-11e4-9c3b-fa9c1c21d975.png)

That's why, :pray: :clap: :clap:

**Comment by sergiiz** [comment]
@lolobosse thanks a lot for this test!

on my fork of lib https://github.com/sergiiz/ShowcaseView/commits/upstream here is a fix for landscape also, but @rahuliyer95 made some updates in his fork, and also see @rharter comments on my pull request https://github.com/amlcurran/ShowcaseView/pull/272 about issues on Nexus 7.

Hope to make some more tests during next week and make one more pull request which will cover fix for all cases

**Comment by lolobosse** [comment]
Ok, great I have Nexus 4, 6, 7 and a bunch of HTCs... Do not hesitate to ask if I can test something else.

**Comment by kazaky** [comment]
@sergiiz Thanks man,
Tried your latest  https://github.com/sergiiz/ShowcaseView/commits/upstream 
& worked very well for the button in both orientation  :+1: 

now am having a problem with "Text margins", 
In case if we have an on Screen NavigationBar!
Can any buddy please help with this Bug
Thanks 
![screenshot_2015-04-12-01-44-52](https://cloud.githubusercontent.com/assets/4202132/7103720/0a439d6a-e0b6-11e4-968f-35851d232384.png)
![screenshot_2015-04-12-01-44-40](https://cloud.githubusercontent.com/assets/4202132/7103721/0a468750-e0b6-11e4-8ed9-c43b1d8986d8.png)
