### ISSUE TITLE
Wiki:i cant find any tutorial

### ISSUE THREAD

**Issue by iranfast** [amlcurran/ShowcaseView#253]
hi,

i cant find any tutorial for multi Showcase on version 5.

and how can i change cling color?

thanks

**Comment by paulcanning** [comment]
I'd also like to know how to use the multi target feature.

The sample app that is on Google Play has it, but the code for the Sample app doesn't, I'm guessing its not been updated properly.

**Comment by paulcanning** [comment]
found it here https://github.com/amlcurran/ShowcaseView/wiki/Display-showcase-views-sequentially-on-the-same-screen
