### ISSUE TITLE
Support for menu in Toolbar

### ISSUE THREAD

**Issue by naddaf** [amlcurran/ShowcaseView#255]
Alex,
Is that supported? With the new Toolbar in new AppCompat library, I am moving  the CastVideos-android sample app to use toolbar, so I basically have a theme that has no actionbar (inheriting from Theme.AppCompat.Light.NoActionBar) and have a toolbar instead. The Cast icon, defined in the menu, appears in the toolbar so I was wondering if that case is already supported or I need to do some work on your library to have it supported?

Thanks
Ali

**Comment by juanelodelpiero** [comment]
In my case worked when i used the following 
oncreate(Bundle savedInstance){
  ToolBar toolbar = (ToolBar) findViewById(R.id.myidtoolbar);
  toolbar.inflateMenu(R.menu.mymenu);
  setSupportActionBar(toolbar);

   ViewTarget target = new ViewTarget(toolbar.findViewById(R.id.myIdmenu));
   ShowcaseView.Builder(this, true)
   .setTarget(target)
   .build();
  
}


But use too

onCreateOptionsMenu(Menu menu){
  getMenuInflater().inflate(R.menu.mymenu, menu);
  return true;
}

**Comment by pavelsust** [comment]
thanks a lot it saves my full night. how i works.


    Toolbar toolbar;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        toolbar = (Toolbar) findViewById(R.id.toolbar);
        toolbar.inflateMenu(R.menu.menu_main);
        setSupportActionBar(toolbar);

        ViewTarget target = new ViewTarget(toolbar.findViewById(R.id.menu_id_launcher));
        new ShowcaseView.Builder(this)
                .setContentTitle("Its My Navigation Drawer")
                .setContentText("Click here and you will get options to navigate to other sections.")
                .useDecorViewAsParent() //this is the difference
                .setTarget(target)
                .build();
    }


and always show the menu in the toolbar like this 

   <item
        android:id="@+id/menu_id_launcher"
        android:orderInCategory="100"
        android:icon="@mipmap/ic_launcher"
        android:title="@string/action_settings"
        app:showAsAction="always" />

**Comment by Bharavi26** [comment]
how can we display showcase on menu item in fragment?
