### ISSUE TITLE
ShowCaseView shape

### ISSUE THREAD

**Issue by orestis131** [amlcurran/ShowcaseView#256]
How can I adjust ShowCaseView shape to the specific view shape? e.g to the dimensions of a rectangle button (instead of the default circle) ?

**Comment by registercosmo** [comment]
Same. Usually, I want rectangle view to highlight some list item, toolbar or the tabbar. However, ellipse is also welcome.

**Comment by angel1307** [comment]
I agree....

**Comment by vamshi3009** [comment]
Can I know how to get the rectangle shape to highlight the listview?

**Comment by amlcurran** [comment]
See the sample custom drawer, which uses a rectangle to draw:

https://github.com/amlcurran/ShowcaseView/blob/master/sample/src/main/java/com/github/amlcurran/showcaseview/sample/CustomShowcaseActivity.java
