### ISSUE TITLE
Showcase Outer and Inner Radius not changing

### ISSUE THREAD

**Issue by bpr10** [amlcurran/ShowcaseView#259]
I am trying to set the outer radius and iinner radius to 50 and 60 dp and my showcase radius is 40 dp .But its not getting set.

**Comment by vyscond** [comment]
The solution highlighted by @bpr10 is fine, but what if i want more than one set of values? Sometimes i want to highlight a medium icon (24x24)  or just a big one  (43x43). How can i achieve it?

I don't know much about the project, but if the library can change the radius from an attrs.xml i think it can be done from activities/fragments classes.

**Comment by bpr10** [comment]
@vyscond   Try working from backwards .Starting form where the call is being made to the dimens file . Instead make the size of circles taken from the calling method and similarly try your way back to the Showcaseview.Builder nad make a method to set circle radius there . That can be done i guess .

**Comment by vyscond** [comment]
ok @bpr10 thanks for pointing the start, but i can't done it right now. :/
