### ISSUE TITLE
Threading issue in sample AnimationSampleActivity.java

### ISSUE THREAD

**Issue by eschlot** [amlcurran/ShowcaseView#268]
Showcase 5.0.0
ShowcaseView/sample/src/main/java/com/github/amlcurran/showcaseview/sample/animations/AnimationSampleActivity.java

Hi!

When I used the code from this sample in my project I found the following issue: 
The call to hide (line 71) comes so early that I get a null pointer exception later in StandardShowCase.java, method erase because the object bitmapBuffer is already null. 

I worked around the same by calling hide form a Worker Thread some millseconds later. 

I did not face the probe in Your sample app but only in mine where some OpenGL Redering is happening in parallel and the load on the processor might be higher.  Moreover I get this on irregular base.

Greetings
Eckart Schlottmann

**Comment by amlcurran** [comment]
OK, I suspect this might be difficult to diagnose, but if you get any more ideas or ways to reproduce this, let me know!
