### ISSUE TITLE
How to show multiple showcase for multiple item on same time ?

### ISSUE THREAD

**Issue by sachinbhanot** [amlcurran/ShowcaseView#271]
Hi ,
I want to show the multiple showitems for multiple view?

**Comment by yuriy-blinov** [comment]
Hello,
You can find an example here https://github.com/amlcurran/ShowcaseView/blob/master/sample/src/main/java/com/github/amlcurran/showcaseview/sample/animations/AnimationSampleActivity.java
After the "Next" button is tapped showcase properties(target, titles) are changed in the Click listener.
