### ISSUE TITLE
Detail Text does not wrap if no target

### ISSUE THREAD

**Issue by doodlleus** [amlcurran/ShowcaseView#274]
If Target.NONE or just no target is selected then I am seeing an issue where the detail text is not wrapping. The only way I am able to get around this at the moment is by setting an arbitrary target for something offscreen

**Comment by AzureusSme** [comment]
I'm having the same problem, but i don't know how to set a target offscreen. The doc is too shitty. :s

**Comment by mjtrujill** [comment]
Looking at the Target.NONE code, it uses a point at (1000000,1000000).  Perhaps the code is getting confused and believes that you have an extremely wide screen and thus no need to wrap the text.  I changed from "Target.NONE" to using a PointTarget with a location off screen but only in the y-axis.  The below change solved my no wrap problem.

		    .setTarget(new PointTarget(0,1000000)) //workaround for Target.NONE

**Comment by brainvision** [comment]
doesn't work to me! :(

**Comment by sureshs592** [comment]
@mjtrujill Thanks for the workaround! Works perfectly. :)
