### ISSUE TITLE
How to block the touches on any target which is rounded by circle?

### ISSUE THREAD

**Issue by sachinbhanot** [amlcurran/ShowcaseView#278]
How to block the touches of target which is highlighted or rounded circle?

**Comment by madcyph3r** [comment]
Add this to the showcaseview.java

private boolean blockShowcaseTouch = false;
public void setBlockShowcaseTouch(boolean blockShowcaseTouch) {
        this.blockShowcaseTouch = blockShowcaseTouch;
}

Search for:
return blockTouches && distanceFromFocus > showcaseDrawer.getBlockedRadius();

and add above it:
if(blockShowcaseTouch) {
        return blockShowcaseTouch;
}



now you can add to your ShowcaseView this:
sv.setBlockShowcaseTouch(true);

**Comment by yhercouet** [comment]
Thanks for this, I was looking for the exact same modification.
