### ISSUE TITLE
Is it possible to use this library in eclipse ?

### ISSUE THREAD

**Issue by shifarshifz** [amlcurran/ShowcaseView#281]

**Comment by hatpick** [comment]
Did you try to google your question before adding a new "issue" here?

You just need to reorganize things a little bit. The easiest way I've found is:

Download the source code from github or the zip file in their website
Create a new folder (i.e.: 'ShowcaseView') in a different place.
Go to /library/main/src and copy AndroidManifest.xml and res folder to the new ShowcaseView folder.
Copy the contents inside /library/main/src/java to a new folder src inside ShowcaseView
Open Eclipse, go to File > New > Project... > Android Project from Existing Code and select as Root Directory the ShowcaseView folder where you have copied java and resource files (maybe check 'Copy projects into workspace' if that's what you want).
Once the project is imported, right click on it > Properties... > Android, select Project Build Target: Android 4.4.2 (API Level 19) and check 'Is Library'
Now you will have a library project ready to be used from other Eclipse projects.

from stackoverflow
