### ISSUE TITLE
Wrong positioning of close button

### ISSUE THREAD

**Issue by dirkam** [amlcurran/ShowcaseView#292]
I try to add a showcaseview for a FAB (view in the bottom right corner of the screen) in a fragment but the close button overlaps the view.
I've tested it on a few devices and it's the same on all of them.

![image](https://cloud.githubusercontent.com/assets/6302839/6789281/75c63eb0-d19f-11e4-9deb-6fbe6cf06f84.png)

**Comment by tomredman** [comment]
+1 would love to include a positioning api for the button

**Comment by Harti** [comment]
@amlcurran 
Why did this get closed without any comment?

Before I go on to criticize it, I want to stress that this library is amazing. Frankly, though, I feel like it should be able to figure out for itself whether or not the button is on top of the target point. Had you made the button accessible with a getter, I'd have implemented that as well (On that note, I'm glad the library's classes aren't final at least).

I suck at making actual PRs that pass tests, so here's what I would do:
* target.getPoint
* get position and size of button after laying it out
* check if it's overlapping
* if it does, align it to the left instead
* ???
* profit

---

For anyone else requiring this. #66 added functionality to pass one's own LayoutParams object to a function called `setButtonPosition` after the ShowcaseView has been built, so you have to call it on the ShowcaseView object and also make sure to set the correct margins on the LayoutParams. 

Unfortunately, documentation on this feature is very poor and you'll go through some trouble trying to find the correct styling.
To streamline this process, I've created a gist extending the Builder class:
https://gist.github.com/Harti/5a3e292b359837bb5da3f22ef746edce

`setButtonAlignment()` accepts any amount of `RelativeLayout.ALIGN_` parameters. You can also add alignment rules with views. 
Make sure you call the methods of the extended class before any of the original Builder's methods or else you won't be able to access them.

```
new ShowcaseViewBuilder(this)
                .setButtonAlignment(RelativeLayout.ALIGN_PARENT_LEFT, RelativeLayout.ALIGN_PARENT_BOTTOM)
                .setButtonMargins(R.dimen.margin, R.dimen.margin, R.dimen.margin, R.dimen.margin)
                .withNewStyleShowcase()
                .setTarget(new ViewTarget(R.id.fab_add_point, this))
                .setContentTitle("ShowcaseView")
                .setContentText("This is highlighting a FAB")
                .hideOnTouchOutside()
                .build();
```

**Comment by Anu07** [comment]
Thanks,it was of big help
