### ISSUE TITLE
insertShowcaseViewWithType cannot be used when the theme has no ActionBar

### ISSUE THREAD

**Issue by justdeko** [amlcurran/ShowcaseView#296]
After a quick search I thought this error was fixed, but it is still appearing when I launch my application:
 ```java.lang.RuntimeException: insertShowcaseViewWithType cannot be used when the theme has no ActionBar```
Is this issue solved yet?
(Here is my code, just in case:
```
new ShowcaseView.Builder(getActivity())
                    .setTarget(new ActionItemTarget(getActivity(), R.id.normal_plus))
                    .setContentTitle("Tutorial")
                    .setContentText("click this button to open the menu)
                    .hideOnTouchOutside()
                    .build();
```
(in fragment, normal_plus is the button I want to target)

**Comment by rcketscientist** [comment]
Are you using a toolbar?  I've been wrapping the target creation for a while as all the changes in material have broken some things in SCV.  Try the code in this post:

https://github.com/amlcurran/ShowcaseView/issues/203#issuecomment-78117448
