### ISSUE TITLE
Action bar menu items aren't targetable

### ISSUE THREAD

**Issue by boeserwolf91** [amlcurran/ShowcaseView#315]
One of your last commits changed the behavior of the showcase view. The showcase view isn't useable for action bar menu items anymore if the default action bar is used.  

I noticed that [this lines](https://github.com/amlcurran/ShowcaseView/blob/master/library/src/main/java/com/github/amlcurran/showcaseview/ShowcaseView.java#L158-L160) may produce negative values which makes the showcaseview to disappear. Just the button stays alive. 
After that I set the y value to 0 manually. I observed that the showcase view doesn't overlay the action bar anymore.

**Comment by amlcurran** [comment]
If you look at the release notes for [5.3.0](https://github.com/amlcurran/ShowcaseView/releases/tag/5.3.0) you'll see the default behaviour has changed (hence the minor version bump). So if you want it to overlay the action bar, use the method documented there. 

Does using that fix this issue?

**Comment by boeserwolf91** [comment]
oh yes, that fixes this issue. Thank you.

**Comment by amlcurran** [comment]
:+1:
