### ISSUE TITLE
setText does not update view

### ISSUE THREAD

**Issue by rcketscientist** [amlcurran/ShowcaseView#32]
setText does not update the view by itself.  In fact the only way I've found to update an existing view is to change where the showcase is pointing.

In my case I have a tutorial that would simply reuse the showcase and change the text and pointer around.  I ran into the issue when I had a verbose explanation that needed to be split on smaller screens.  The setText didn't cause the showcase to update.

I've also "fixed" the triple parent issue on my device as well as added the ability to showcase contextual action bars, but I'm new to git and don't have time at the moment to figure out how to share this.

**Comment by SvehlaJan** [comment]
Hello.

This problem remain ( version 5.4.1 ) imho.
I build the showcase once and then just want to change text a few times, without having a target. I use:
```
mShowcaseView.setContentTitle("title");
mShowcaseView.setContentText("content);
mShowcaseView.setShowcase(Target.NONE, true);
mShowcaseView.show();
```

and nothing happens. When I change target to some view, showcase updates properly.

Thanks for your great work!

**Comment by amlcurran** [comment]
@SvehlaJan see #373, tracking this issue there
