### ISSUE TITLE
How to use views in sequence on after another ?plz help

### ISSUE THREAD

**Issue by iampawan** [amlcurran/ShowcaseView#325]

**Comment by amlcurran** [comment]
The memory management sample ([here](https://github.com/amlcurran/ShowcaseView/blob/master/sample/src/main/java/com/github/amlcurran/showcaseview/sample/MemoryManagementTesting.java)) has a basic implementation, it shouldn't be difficult to extend this to your use case

**Comment by amlcurran** [comment]
@iampawan does this help you?

**Comment by iampawan** [comment]
@amlcurran  yes thanks !!

**Comment by amlcurran** [comment]
:+1: I hope to make it easier to do soon, too :)
