### ISSUE TITLE
Button background

### ISSUE THREAD

**Issue by Scarfoo** [amlcurran/ShowcaseView#332]
Hi, is it possible to change button background ? I have already tried it using styles, but it was not working.

**Comment by amlcurran** [comment]
Not really, but it is possible to change the button for your own one - see the sample here:
https://github.com/amlcurran/ShowcaseView/blob/master/sample/src/main/java/com/github/amlcurran/showcaseview/sample/SampleActivity.java#L78

**Comment by amlcurran** [comment]
Hope that helps?

**Comment by Scarfoo** [comment]
Yeah, thx. :)

**Comment by amlcurran** [comment]
:+1: awesome!
