### ISSUE TITLE
Not working appropriately with activity

### ISSUE THREAD

**Issue by sidsverma** [amlcurran/ShowcaseView#337]
I was trying to incorporate this into my existing activity and it isn't showing up as it usually does(I have tried with fragments and it works like a charm).
I even tried the ".show()" and then it only showed the Okay button without any background. I even tried changing the theme. Also, I tried calling the .show() from onCreate() as well as onResume(). Nothing worked!

**Comment by amlcurran** [comment]
Hmm, are you using single shot? I've noticed that happen once before. 

If you can show some sample code, that'll be really useful

**Comment by sidsverma** [comment]
You are absolutely correct! SingleShot was the problem. Now the problem is solved for me.
Thanks. Btw, what does SingleShot signify?

**Comment by amlcurran** [comment]
It should be that the showcaseview should only ever show once, but as you can see it doesn't work :D will fix it as a bug!

**Comment by sidsverma** [comment]
Actually this is working properly! I didn't know about the single-shot activity behaviour. When I changed the number, it worked.
Thanks.

**Comment by ParitoshBh** [comment]
@sidsverma the singleShot() takes one input. I tried with 2, guessing that the showcaseview will be shown twice but logically as per what @amlcurran wrote, this isn't the expected behaviour. So why the need for a parameter at all? Won't removing it reduce some confusion?

**Comment by sidsverma** [comment]
No, I believe that number signifies a type of tutorial. I mean if you want
a particular tutorial to be shown once and then another tutorial also to be
shown once, you use two different numbers in singleShot.

On Sun, Dec 20, 2015 at 1:45 AM, Paritosh <notifications@github.com> wrote:

> @sidsverma <https://github.com/sidsverma> the singleShot() takes one
> input. I tried with 2, guessing that the showcaseview will be shown twice
> but logically as per what @amlcurran <https://github.com/amlcurran>
> wrote, this isn't the expected behaviour. So why the need for a parameter
> at all? Won't removing it reduce some confusion?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amlcurran/ShowcaseView/issues/337#issuecomment-166021128>
> .
>



-- 
Siddharth Verma
+91 81470 19806

**Comment by amlcurran** [comment]
@ParitoshBh  @sidsverma is correct. For each different place you want a single-shot showcaseview, use a different ID.

**Comment by kolobchanin** [comment]
This workaround worked for me:

int color = firstShowcaseElement.getDrawingCacheBackgroundColor();
firstShowcaseElement.setBackgroundColor(color);

In my case "firstShowcaseElement" - is a parent view of ShowCaseview "target" element.

**Comment by L96Github** [comment]
The same happens to me, but only in the second run. I have a button to show the showcase, when I press it the first time it runs fine on the second run it only shows the button and touch is disabled. Have to press the back button to close activity.

I've tried, using single-shot with a random number so it runs every time, tried @kolobchanin suggestion:
```
 int color = firstShowcaseElement.getDrawingCacheBackgroundColor();
firstShowcaseElement.setBackgroundColor(color);
```
nothing worked...
