### ISSUE TITLE
Change text color

### ISSUE THREAD

**Issue by sidsverma** [amlcurran/ShowcaseView#339]
I couldn't change the text color of my content and title. Any pointers on that?
I tried using .setContentTitlePaint( titleFormat )
and
    TextPaint titleFormat = new TextPaint();
        titleFormat.setColor(0xffffff);

**Comment by amlcurran** [comment]
That should work. I can't remember if the ShowcaseView style is applied afterward, in which case that would overwrite the colour you've set. I'll investigate that.

You can do it in a style using this:
https://github.com/amlcurran/ShowcaseView/blob/master/sample/src/main/res/values/styles.xml#L51

**Comment by sidsverma** [comment]
Thanks a lot! That helped! :)
