### ISSUE TITLE
Using with Fragments!

### ISSUE THREAD

**Issue by rakhtsavelives** [amlcurran/ShowcaseView#345]
How to use showcase view with fragments??

**Comment by dev-JE02** [comment]
I use them the same way with Activity.

**Comment by rakhtsavelives** [comment]
It takes the height and width of component less then zero!!!

**Comment by dev-JE02** [comment]
Could you post your code? And the error you are getting. I just use the same Builder to show the ShowcaseView. Though the context I pass into it is `getActivity()`

**Comment by amlcurran** [comment]
@rakhtsavelives some example code will be great here. Make sure you're creating your ShowcaseView during or after `onActivityCreated(...)`

**Comment by rakhtsavelives** [comment]
I am using it in onCreate() is it the wrong place??

**Comment by amlcurran** [comment]
Yes, try using it in onActivityCreated instead and let me know if that
works

**Comment by rakhtsavelives** [comment]
Thanks, it works when used in onActivityCreated().
