### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getLocationInWindow(int[])' on a null object reference

### ISSUE THREAD

**Issue by akhorevich** [amlcurran/ShowcaseView#355]
Hello! I have some trouble with my Fragment to show ShowCase in it. I don't know how can i fix this problem. Can you help me?
I think, its a trouble in ViewTarget widget id....

![screen](https://cloud.githubusercontent.com/assets/2069292/12409455/42a9bcae-be7b-11e5-9309-24eea4e2bdb7.png)

**Comment by amlcurran** [comment]
When using SCV in a fragment, create the ShowcaseView in onActivityCreated(). You're trying to create the showcase before the view has been inserted into the activity
