### ISSUE TITLE
Title and Text becoming very small,like subtext, when showcase is applied on action bar items

### ISSUE THREAD

**Issue by Saudasadaf** [amlcurran/ShowcaseView#362]
I'am trying to add showcase on action bar items, but Title and text are becoming as subtext. currently I'm using 5.4.0 library. Can you please help me in this scenario.

**Comment by amlcurran** [comment]
Can you post a screenshot please? and the code you're using to display the showcaseview

**Comment by Saudasadaf** [comment]
Resolved .
