### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by Fornori** [amlcurran/ShowcaseView#368]
Hello. On some device I get the next error:
`Caused by java.lang.OutOfMemoryError
android.graphics.BitmapFactory.nativeDecodeAsset (BitmapFactory.java)
android.support.v4.content.res.ResourcesCompat.getDrawable (ResourcesCompat.java:62)
com.github.amlcurran.showcaseview.StandardShowcaseDrawer.<init> (StandardShowcaseDrawer.java:45)
com.github.amlcurran.showcaseview.ShowcaseView.<init> (ShowcaseView.java:127)
com.github.amlcurran.showcaseview.ShowcaseView.<init> (ShowcaseView.java:99)
com.github.amlcurran.showcaseview.ShowcaseView$Builder.<init> (ShowcaseView.java:441)
com.github.amlcurran.showcaseview.ShowcaseView$Builder.<init> (ShowcaseView.java:430)
com.grogard.mobile.postaltrack.ui.parcellist.MainActivity.initShowCase (MainActivity.java:114)
com.grogard.mobile.postaltrack.ui.parcellist.MainActivity.onMenuHelpClick (MainActivity.java:78)
java.lang.reflect.Method.invokeNative (Method.java)
dalvik.system.NativeStart.main (NativeStart.java)`

Any idea how to prevent this?

**Comment by Fornori** [comment]
Closed

**Comment by thilook** [comment]
Do you had any success to work around this issue?
