### ISSUE TITLE
The ShotStateStore.storeShot() call shoudn't be on ShowcaseView.show()?

### ISSUE THREAD

**Issue by sandro-csimas** [amlcurran/ShowcaseView#375]
I'm creating the showcase with singleshot inside Activity.onResume. Sometimes the onResume is called twice and then the showcase appears one above the other. The singleshot should not guarantee that the showcase will be displayed only once?
Actually, the ShotStateStore.storeShot() is called on ShowcaseView.hide().

**Comment by amlcurran** [comment]
Good point, there are a lot of bugs around the single-shot API to the point where I don't recommend using it at the moment. I'll track your issue in the related issue #174

**Comment by sandro-csimas** [comment]
OK @amlcurran. Did you see that the related issue is closed?
Thanks!

**Comment by amlcurran** [comment]
I did not! Opened it again now

**Comment by sandro-csimas** [comment]
OK @amlcurran, do you have any idea when you will see this issue again?
For now i will comment the showcase code because this feature is very important to me.

**Comment by sandro-csimas** [comment]
If you want i can help you providing a pull request. We can discuss the best way to fix the related problem.
