### ISSUE TITLE
could not find element /manifest/appliction

### ISSUE THREAD

**Issue by wuziq** [amlcurran/ShowcaseView#378]
I added:

compile 'com.github.amlcurran.showcaseview:library:5.4.1'

to my .gradle file, but am getting this error:

:processDebugManifest
[C:\myproject\build\exploded-aar\com.github.amlcurran.showcaseview\library\5.4.1\AndroidManifest.xml:1] Could not find element /manifest/application.
[C:\myproject\build\exploded-aar\com.github.amlcurran.showcaseview\library\5.4.1\AndroidManifest.xml:1] Could not find element /manifest/application.
[C:\myproject\build\exploded-aar\com.github.amlcurran.showcaseview\library\5.4.1\AndroidManifest.xml:1] Could not find element /manifest/application.
[C:\myproject\build\exploded-aar\com.github.amlcurran.showcaseview\library\5.4.1\AndroidManifest.xml:1] Could not find element /manifest/application.
[C:\myproject\build\exploded-aar\com.github.amlcurran.showcaseview\library\5.4.1\AndroidManifest.xml:1] Could not find element /manifest/application.
[C:\myproject\build\exploded-aar\com.github.amlcurran.showcaseview\library\5.4.1\AndroidManifest.xml:1] Could not find element /manifest/application.
[C:\myproject\build\exploded-aar\com.github.amlcurran.showcaseview\library\5.4.1\AndroidManifest.xml:1] Could not find element /manifest/application.
:processDebugManifest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugManifest'.
> Manifest merging failed. See console for more info.

I'm probably missing something but it seems the fix is to add an <application/> tag to the library's manifest:  https://groups.google.com/forum/#!topic/adt-dev/wFnAOAmYCSs

**Comment by amlcurran** [comment]
What version of the build tools are you using?

**Comment by wuziq** [comment]
Hi Alex, sorry about the delay.

Your question provided the hint I needed.  It turns out I was using an old version:  0.9.2.  I have since upgraded to 1.5.0, and the problem has gone away.  Sorry about that, and thank you!

**Comment by amlcurran** [comment]
No problem! I guessed as the article you linked was using old versions of the build tools :) happy developing!
