### ISSUE TITLE
Mention or Credit inside the app

### ISSUE THREAD

**Issue by akdsouza** [amlcurran/ShowcaseView#380]
Hey there!
I'm developing an android app, not as an enterprise or company but rather as a developer as I learn android. I've used the ShowcaseView in my app and would like to credit or mention copyright to you in settings. What is the best way to let user's know that my app uses your library?
P.S: @amlcurran Thanks for the awesome work!

**Comment by amlcurran** [comment]
A simple declaration is fine! Just add the library name, my name, a link, and the licence (Apache 2.0). I'm not too fussed about how you do so :) 

Please let me know what your app is called so I can take a look :)
