### ISSUE TITLE
Showcaseview flashes when switching to multiple targets in sequence

### ISSUE THREAD

**Issue by akdsouza** [amlcurran/ShowcaseView#381]
I'm using fragments. The issue primarily occurs if you set the showcase view to one target and on click of a button, switch to show the showcase for other targets in a sequence. So as the showcase view switches between different UI elements, you see the background fragment flash as the showcase view lays out for different targets. Is there some way to resolve this such that  the highlighting circle of the showcase view seems to just slide from one target to the next, like a spotlight? Note that the showcase view background is an opaque color. Any help is appreciated.

**Comment by amlcurran** [comment]
Can you record a video of what is happening? There is a sample using animations (https://github.com/amlcurran/ShowcaseView/blob/master/sample/src/main/java/com/github/amlcurran/showcaseview/sample/animations/AnimationSampleActivity.java) which should help you out, although there is a related issue #377 which means there's a bug with the library as it currently is.

**Comment by akdsouza** [comment]
I've just released my app on play store where you can see the issue mentioned. Download it here:
https://play.google.com/store/apps/details?id=com.anupdsouza.perkitna&hl=en
Use the guide in each of the two tabs to see the flashing as the targets change. Structurally, the tabs are fragments enclosed in a tab pager inside the main activity.

**Comment by akdsouza** [comment]
@amlcurran any chance you could take a look?

**Comment by amlcurran** [comment]
Hi! I took a look at your app and I think the bug is related to #377. I've release ShowcaseView 5.4.2 now (https://github.com/amlcurran/ShowcaseView/releases/tag/5.4.2), can you see if using that version fixes your issue?

**Comment by akdsouza** [comment]
Thanks @amlcurran . I will update to the latest release and check.

**Comment by amlcurran** [comment]
thanks, please let me know if the issue is fixed!

**Comment by akdsouza** [comment]
Hi @amlcurran , I'm happy to report that the release 5.4.3 fixes the issue :) 
Keep up the good work ! 👍
