### ISSUE TITLE
showcase is positioned behind cardviews

### ISSUE THREAD

**Issue by seba123neo** [amlcurran/ShowcaseView#397]
I have 2 cardviews on my activity and when I want to show the showcase, it appears behind the cardviews.

Any solution for this ?

**Comment by amlcurran** [comment]
How strange - how are you showing them? It isn't in a dialog or anything? 

If you could provide a screenshot this would be really useful

**Comment by seba123neo** [comment]
here is the screenshot: look how the showcase is behind the cardview: the code is this:

```
ViewTarget navigationButtonViewTarget = ViewTargets.navigationButtonViewTarget(toolbar);
            new ShowcaseView.Builder(this)
                    .setTarget(navigationButtonViewTarget)
                    .singleShot(45)
                    .setContentText("Texttttt")
                    .build()
                    .show();
```

![screenshot_2016-06-07-09-47-09](https://cloud.githubusercontent.com/assets/9873666/15858061/05254f3c-2c95-11e6-8526-eab501c0e02a.png)

**Comment by seba123neo** [comment]
but in another activity i have cardviews too and works perfect, is weird...

**Comment by seba123neo** [comment]
solved !!! the problem was that it was putting the code (onCreate) before the controls are loaded, put it at the end and it works !!! sorry

**Comment by amlcurran** [comment]
Not a problem, glad you fixed it! 👍
