### ISSUE TITLE
Can you public hasShot() method in ShowcaseView class?

### ISSUE THREAD

**Issue by phuoclk1989** [amlcurran/ShowcaseView#399]
I need to show a welcome dialog when open app and if this is first time open app, i need show showcase and don't show welcome dialog. So, i need hasShot() method to know is it first time open app.

**Comment by Burtan** [comment]
That might be a good idea. In the meantime you can use the following:

`SharedPreferences internal = getSharedPreferences("showcase_internal", Context.MODE_PRIVATE);
        boolean shot = internal.getBoolean("hasShot" + name, false);`

**Comment by phuoclk1989** [comment]
Thank you so much!
