### ISSUE TITLE
How do I hide the showcase view when the showcase view's target is clicked?

### ISSUE THREAD

**Issue by VisheshVadhera** [amlcurran/ShowcaseView#411]
Let's say that my showcase view's target is a floating action button (called FAB1) and my showcase view is called SCV1. In order to hide the showcase view when someone clicks on the floating action button I am thinking of adding an onClickListener on the floating action bar and doing this:

`FAB1.setOnClickListener(new View.OnClickListener() {

            @Override

            public void onClick(View v) {

                if(SCV1.isShowing){

                	SCV1.hide();

                }

              //Do further action after FAB1 is clicked (e.g. open an activity.)

            }

        });`

Is there a better way to achieve this, without attaching an onClickListener to my FAB1, something which is provided by the library itself?

**Comment by 10K-with-AI-Enterprise-Edition** [comment]
I found the solution:
```
final ShowcaseView showCaseView = new ShowcaseView.Builder(this)
                .withMaterialShowcase()
                .setContentTitle("Tutorial 1: Pick a Goal (1/x)")
                .setContentText("Tab plus button...")
                .setTarget(new ViewTarget(R.id.fakeFAB, this))
                .replaceEndButton(R.layout.tutorial_fake_button)
                .build();

// whereever you want to show:
showCaseView.show();

// whereever you want to hide:
showCaseView.hide();
```
