### ISSUE TITLE
Is there any way to adjust the button's position?

### ISSUE THREAD

**Issue by fantapsody** [amlcurran/ShowcaseView#48]
I found the confirm button is placed at the right bottom of the view on default, this is not proper when I need to showcase some view just at the position, as the button would overlap that view. Although there is an option to hide the button, it cannot be set outside the class, such as in a builder. Is there any way to adjust the button's position without modifying the code?

**Comment by vyscond** [comment]
where is the example? now we are using Floating Action buttons. It's good to change the button to left. :(

**Comment by hatpick** [comment]
```
RelativeLayout.LayoutParams params = new RelativeLayout.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT);
///Customize it here
showcaseView.setButtonPosition(params);
```
